// Mocks generated by Mockito 5.0.16 from annotations
// in nu_and_morty/test/core/data/repository/nu_marketplace_data_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nu_and_morty/core/data/remote/nu_marketplace_remote_data_source.dart'
    as _i3;
import 'package:nu_and_morty/features/home/data/models/get_costumer_and_offers_model.dart'
    as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGetCostumerAndOffersModel_0 extends _i1.Fake
    implements _i2.GetCostumerAndOffersModel {}

/// A class which mocks [NuMarketplaceRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNuMarketplaceRemoteDataSource extends _i1.Mock
    implements _i3.NuMarketplaceRemoteDataSource {
  MockNuMarketplaceRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.GetCostumerAndOffersModel> getCostumerAndOffersModel() =>
      (super.noSuchMethod(Invocation.method(#getCostumerAndOffersModel, []),
              returnValue: Future<_i2.GetCostumerAndOffersModel>.value(
                  _FakeGetCostumerAndOffersModel_0()))
          as _i4.Future<_i2.GetCostumerAndOffersModel>);
  @override
  String toString() => super.toString();
}
